### ISSUE TITLE
.NET Core 1.1

### ISSUE THREAD

**Issue by adamhathcock** [CL0SeY/dotnet-mono-node-docker#1]
First off, thanks for these and putting the images on Docker Hub.

You've got .NET Core SDK 1.1 on github with mono: https://hub.docker.com/r/cl0sey/dotnet-mono-docker/tags/

Any chance of updating this with that soon?  Thanks!

**Comment by CL0SeY** [comment]
Sorry for the delay, didn't see this here :)

I will do some work to get the tags in the same layout as the parent image.

Cheers!

**Comment by adamhathcock** [comment]
much appreciated

**Comment by CL0SeY** [comment]
What are your thoughts on nodejs versions? It's starting to get a bit complicated with all the different versions of dotnet and node flying around. Would nodejs 6.x be ok, considering it's LTS?

I'm thinking maybe:
Latest: alias of 1.1-sdk
1.0-sdk (w/nodejs 6) [for building dotnet apps with a node dependency, and running if you choose]
1.1-sdk (w/nodejs 6) [for building dotnet apps with a node dependency, and running if you choose]
1.0-runtime (w/nodejs 6) [for running dotnet + node apps, not building]
1.1-runtime (w/nodejs 6) [for running dotnet + node apps, not building]

**Comment by adamhathcock** [comment]
Yeah, I just use it for packaging.  I think the LTS is probably what is "officially" used.

**Comment by CL0SeY** [comment]
New builds should start rolling out now: https://hub.docker.com/r/cl0sey/dotnet-mono-node-docker/builds/

Hopefully haven't stuffed anything up :) 

I also updated the master branch of the base image to match what was being build on docker hub: https://github.com/CL0SeY/dotnet-mono-docker/

**Comment by adamhathcock** [comment]
works, great.  thanks!

**Comment by CL0SeY** [comment]
Sweet, I've merged the changes into master now.
